Repository NationalGenomicsInfrastructure/LIMS2DB, pull requests merged in 2023-10, with the labels that each got.

#131 Add support for Illumina DNA PCR-free protocol
  LIMS2DB/objectsDB/process_categories.py
  VERSIONLOG.md
  docs/process_categories.rst
Labels: validation

#132 Add missing sequencing step IDs
  LIMS2DB/classes.py
  VERSIONLOG.md
  scripts/workset_upload_sql.py
Labels: bug, no validation

#133 Update Johannes aggregate qc running note script to run as cronjob
  VERSIONLOG.md
  requirements.txt
  scripts/escalation_running_notes.py
Labels: no validation

#134 Support CytAssist protocol; Clear hardcoded step ids
  LIMS2DB/classes.py
  LIMS2DB/flowcell_sql.py
  LIMS2DB/objectsDB/process_categories.py
  VERSIONLOG.md
  docs/process_categories.rst
  scripts/workset_upload_sql.py
Labels: enhancement, no validation

#135 Support workset with multiple replicates of the same sample
  LIMS2DB/classes.py
  VERSIONLOG.md
Labels: bug, enhancement, no validation
