Repository NationalGenomicsInfrastructure/LIMS2DB, pull requests merged in 2023-11, with the labels that each got.

#137 Add key names for new UDFs for setup ws
  LIMS2DB/classes.py
  VERSIONLOG.md
Labels: bug, enhancement, validation

#138 Fix document update conflict error with escalation RN
  VERSIONLOG.md
  scripts/escalation_running_notes.py
Labels: bug, no validation

#139 Fix order portal overwrite
  LIMS2DB/classes.py
  VERSIONLOG.md
Labels: no validation

#140 Fix bug of wrong data type
  LIMS2DB/classes.py
  VERSIONLOG.md
  scripts/workset_upload_sql.py
Labels: bug, no validation
